name: example
description: An example app.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  enum_to_string:
  route_observer_mixin:
    path: ..
  provider:
  state_notifier:
  flutter_state_notifier:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
