name: example
description: An example app.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cupertino_icons:
  enum_to_string:
  flutter:
    sdk: flutter
  flutter_state_notifier:
  provider:
  route_observer_mixin:
    path: ..
  state_notifier:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
